const classic1 = loadMusic("classic1");
const classic2 = loadMusic("classic2");
const classic3 = loadMusic("classic3");
const classic4 = loadMusic("classic4");
const music = require("musicinjector");
music.clearAllTracks("ambientMusic");
music.clearAllTracks("darkMusic");
music.clearAllTracks("bossMusic");
music.addTrack(classic1, "ambientMusic");
music.addTrack(classic2, "ambientMusic");
music.addTrack(classic3, "ambientMusic");
music.addTrack(classic4, "ambientMusic");
music.addTrack(classic1, "darkMusic");
music.addTrack(classic2, "darkMusic");
music.addTrack(classic3, "darkMusic");
music.addTrack(classic4, "darkMusic");
music.addTrack(classic1, "bossMusic");
music.addTrack(classic2, "bossMusic");
music.addTrack(classic3, "bossMusic");
music.addTrack(classic4, "bossMusic");
