const classic1 = loadMusic("classic1");
const classic2 = loadMusic("classic2");
const classic3 = loadMusic("classic3");
const classic4 = loadMusic("classic4");
const toaster1 = loadMusic("toaster1");
const music = require("musicinjector");
//music.clearAllTracks("ambientMusic");
//music.clearAllTracks("darkMusic");
//music.clearAllTracks("bossMusic");
music.addTrack(classic1, "ambientMusic");
music.addTrack(classic2, "ambientMusic");
music.addTrack(classic3, "ambientMusic");
music.addTrack(classic4, "ambientMusic");
music.addTrack(toaster1, "darkMusic");
